blueprint:
  name: "IKEA Bilresa Scroll Wheel – Brightness Control (Right & Left)"
  description: "Universal brightness control for IKEA Bilresa Scroll Wheel with separate configurations for clockwise and counter-clockwise rotation"
  domain: automation
  input:
    scrollwheel_right_event_entity:
      name: "Scroll Wheel Event Entity – Clockwise Rotation"
      description: "Event entity of the scroll wheel for clockwise rotation"
      selector:
        entity:
          domain: event

    scrollwheel_left_event_entity:
      name: "Scroll Wheel Event Entity – Counter-clockwise Rotation"
      description: "Event entity of the scroll wheel for counter-clockwise rotation"
      selector:
        entity:
          domain: event

    target_light:
      name: "Target Light"
      description: "Light to be controlled"
      selector:
        entity:
          domain: light

    scroll_right_direction:
      name: "Action on Clockwise Rotation"
      description: "What should happen on clockwise rotation?"
      selector:
        select:
          options:
            - label: "Increase Brightness"
              value: "brighten"
            - label: "Decrease Brightness"
              value: "dim"
      default: "brighten"

    scroll_left_direction:
      name: "Action on Counter-clockwise Rotation"
      description: "What should happen on counter-clockwise rotation?"
      selector:
        select:
          options:
            - label: "Increase Brightness"
              value: "brighten"
            - label: "Decrease Brightness"
              value: "dim"
      default: "dim"

    brightness_per_step_right:
      name: "Brightness Per Step – Right (%)"
      default: 5
      selector:
        number:
          min: 1
          max: 20

    brightness_per_step_left:
      name: "Brightness Per Step – Left (%)"
      default: 5
      selector:
        number:
          min: 1
          max: 20

    startup_brightness_right:
      name: "Startup Brightness When Turning On – Right (%)"
      default: 20
      description: "Brightness in % with which the light is turned on when rotating clockwise"
      selector:
        number:
          min: 5
          max: 50

    startup_brightness_left:
      name: "Startup Brightness When Turning On – Left (%)"
      default: 20
      description: "Brightness in % with which the light is turned on when rotating counter-clockwise"
      selector:
        number:
          min: 5
          max: 50

trigger:
  - platform: state
    entity_id: !input scrollwheel_right_event_entity
    id: "right_scroll"
  - platform: state
    entity_id: !input scrollwheel_left_event_entity
    id: "left_scroll"

action:
  - variables:
      is_right_scroll: "{{ trigger.id == 'right_scroll' }}"
      scroll_direction_right: !input scroll_right_direction
      scroll_direction_left: !input scroll_left_direction
      bright_step_right: !input brightness_per_step_right
      bright_step_left: !input brightness_per_step_left
      startup_bright_right: !input startup_brightness_right
      startup_bright_left: !input startup_brightness_left
      target_entity: !input target_light

      # Determine direction based on trigger
      direction: >-
        {% if is_right_scroll %}
          {{ 1 if scroll_direction_right == 'brighten' else -1 }}
        {% else %}
          {{ 1 if scroll_direction_left == 'brighten' else -1 }}
        {% endif %}

      # Determine brightness per step
      bright_step: "{{ bright_step_right if is_right_scroll else bright_step_left }}"

      # Determine startup brightness
      startup_bright: "{{ startup_bright_right if is_right_scroll else startup_bright_left }}"

      # Extract event type
      event_type_str: "{{ state_attr(trigger.entity_id, 'event_type') }}"

      # Calculate press count
      press_count:
        "{{ trigger.to_state.attributes.totalNumberOfPressesCounted | int(1) }}"

      # Calculate brightness change
      brightness_change: "{{ (bright_step | int(5) * press_count | int(1) * direction) }}"

      # Check status
      light_on: "{{ states(target_entity) == 'on' }}"
      current_brightness: "{{ (state_attr(target_entity, 'brightness') or 0) | int(0) }}"
      brightness_in_pct: "{{ ((current_brightness / 255) * 100) | round(1) }}"

      # Calculate new brightness with clamp
      raw_brightness: "{{ (startup_bright | int(20)) + brightness_change }}"
      new_brightness: >-
        {% set b = raw_brightness | int %}
        {% if b < 10 %}
          10
        {% elif b > 100 %}
          100
        {% else %}
          {{ b }}
        {% endif %}

  - if:
      - condition: template
        value_template: "{{ light_on }}"
    then:
      # Light is ON – control with brightness_step_pct
      - if:
          - condition: template
            value_template: "{{ press_count < 8 or direction > 0 }}"
        then:
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_step_pct: "{{ brightness_change }}"
        #else:
          # On extreme scroll → turn off
        #  - service: light.turn_off
        #    target:
        #      entity_id: !input target_light
    else:
      # Light is OFF
      - if:
          - condition: template
            value_template: "{{ direction > 0 }}"
        then:
          # Increase brightness → Turn on light with start value and then adjust
          - service: light.turn_on
            target:
              entity_id: !input target_light
            data:
              brightness_pct: "{{ new_brightness | int }}"
        else:
          # Decrease brightness → Light stays off
          - service: light.turn_off
            target:
              entity_id: !input target_light

mode: queued
max: 20
